name: mirifanet
description: Realizando Sueños.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  firebase: ^8.0.0
  firebase_db_web_unofficial: ^0.0.2
  async_builder: ^1.2.0
  toast: any
  firebase_auth: ^0.18.4+1
  email_validator: ^2.0.1
  flutter_auth_buttons: ^0.10.0
  firebase_core: ^0.5.2
  curved_navigation_bar: ^1.0.3
  firebase_image: ^0.3.0
  firebase_storage: ^5.0.1
  flutter_swiper: ^1.1.4
  firebase_database: ^4.3.0
  http: ^0.11.3
  share_plus: ^1.0.0
  share_plus_web: ^0.1.0
  transformer_page_view: ^0.1.6
  flutter_page_indicator: ^0.0.3
  carousel_slider: ^4.1.1
  google_sign_in: ^4.5.9
  meta: ^1.7.0
  url_launcher: ^5.7.10






dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.2.1
flutter_icons:
  image_path_web: 'assets/iconoM.png'
  image_path_android: 'assets/iconoM.png'
  image_path_ios: 'assets/iconoM.png'
  adaptive_icon_background: 'assets/iconoM.png'
  adaptive_icon_foreground: 'assets/iconoM.png'
  adaptive_icon_round: 'assets/iconoMd.png' #! (Optional)
  ios: false
  android: false
  web: true
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
